<a href="https://colab.research.google.com/github/anashr18/Kaggle_B/blob/main/My_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# libraries
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import scale



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!ls /content/drive/My\ Drive/RealLifeMLPackt/DATA/

letter-recognition.csv	Spam.csv  Spam.txt  test.csv  train.csv


In [ ]:
# dataset
letters = pd.read_csv("/content/drive/My Drive/RealLifeMLPackt/DATA/SVM/letter-recognition.csv")

In [ ]:
letters.shape

(20000, 17)

In [ ]:
letters.iloc[0:20,0]

0     T
1     I
2     D
3     N
4     G
5     S
6     B
7     A
8     J
9     M
10    X
11    O
12    G
13    M
14    R
15    F
16    O
17    C
18    T
19    J
Name: letter, dtype: object

In [ ]:
print(letters.columns)

Index(['letter', 'xbox ', 'ybox ', 'width ', 'height', 'onpix ', 'xbar ',
       'ybar ', 'x2bar', 'y2bar ', 'xybar ', 'x2ybar', 'xy2bar', 'xedge ',
       'xedgey', 'yedge ', 'yedgex'],
      dtype='object')


In [ ]:
print(np.sort(letters['letter'].unique()))

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']


In [ ]:
=(letters.groupby('letter'))

In [ ]:
X = letters.drop("letter",axis = 1)
Y = letters["letter"]

In [ ]:
X_scaled = scale(X)
X_scaled

array([[-1.0576983 ,  0.29187713, -1.05327668, ..., -0.21908163,
        -1.4381527 ,  0.12291107],
       [ 0.51038497,  1.5023577 , -1.05327668, ..., -0.21908163,
         0.12008142,  1.35944092],
       [-0.01230945,  1.19973756,  0.43590966, ..., -0.8656262 ,
        -0.26947711,  0.74117599],
       ...,
       [ 1.03307939,  0.59449727,  0.43590966, ...,  2.36709667,
        -0.65903564, -2.35014863],
       [-1.0576983 , -1.22122359, -0.55688123, ...,  0.42746295,
         0.50963994,  0.12291107],
       [-0.01230945,  0.59449727,  0.43590966, ..., -0.8656262 ,
        -0.65903564,  0.12291107]])

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size = 0.3, random_state = 101 )

In [ ]:
model_linear = SVC(kernel="rbf")
model_linear.fit(X_train,Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
Y_pred = model_linear.predict(X_test)

In [ ]:
metrics.accuracy_score(y_true = Y_test, y_pred = Y_pred)

0.9383333333333334

In [ ]:
conf_mat = metrics.confusion_matrix(Y_test, Y_pred)
conf_mat

array([[205,   0,   0,   1,   0,   0,   0,   0,   0,   1,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   2,   0],
       [  0, 205,   0,   3,   1,   0,   1,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   6,   1,   0,   0,   0,   0,   1,   0,   0],
       [  0,   0, 213,   0,   5,   0,   7,   1,   0,   0,   0,   0,   0,
          0,   4,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   4,   0, 234,   0,   0,   1,   3,   0,   0,   0,   0,   0,
          3,   1,   0,   0,   2,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 221,   1,   9,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   2],
       [  0,   0,   0,   1,   0, 215,   1,   1,   1,   0,   0,   0,   0,
          1,   0,   1,   0,   0,   1,   3,   0,   0,   0,   0,   0,   0],
       [  0,   0,   3,   4,   1,   1, 202,   0,   0,   0,   0,   1,   1,
          0,   2,   0,   0,   1,   0,   0,   

In [ ]:
conf_mat[:,0]

array([205,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   2,   0])

In [ ]:
print(metrics.classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           A       0.99      0.98      0.98       209
           B       0.81      0.94      0.87       218
           C       0.98      0.93      0.95       230
           D       0.89      0.94      0.92       248
           E       0.92      0.94      0.93       234
           F       0.91      0.96      0.93       225
           G       0.86      0.92      0.89       219
           H       0.91      0.82      0.86       217
           I       0.96      0.90      0.93       215
           J       0.94      0.94      0.94       220
           K       0.97      0.89      0.93       245
           L       1.00      0.94      0.97       237
           M       0.97      0.96      0.97       234
           N       0.94      0.95      0.95       251
           O       0.90      0.95      0.92       221
           P       0.98      0.89      0.94       265
           Q       0.94      0.94      0.94       235
           R       0.83    

In [ ]:
def my_custom_loss_func(X_train_scaled, Y_train_scaled):
    error, M = 0, 0
    for i in range(0, len(Y_train_scaled)):
        z = (Y_train_scaled[i] - M)
        if X_train_scaled[i] > M and Y_train_scaled[i] > M and (X_train_scaled[i] - Y_train_scaled[i]) > 0:
            error_i = (abs(Y_train_scaled[i] - X_train_scaled[i]))**(2*np.exp(z))
        if X_train_scaled[i] > M and Y_train_scaled[i] > M and (X_train_scaled[i] - Y_train_scaled[i]) < 0:
            error_i = -(abs((Y_train_scaled[i] - X_train_scaled[i]))**(2*np.exp(z)))
        if X_train_scaled[i] > M and Y_train_scaled[i] < M:
            error_i = -(abs(Y_train_scaled[i] - X_train_scaled[i]))**(2*np.exp(-z))
    error += error_i
    return error

In [ ]:
# creating a KFold object with 5 splits 
folds = KFold(n_splits = 5, shuffle = True, random_state = 101)

# specify range of hyperparameters
# Set the parameters by cross-validation
hyper_params = [ {'gamma': [1e-2, 1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]}]


# specify model
model = SVC(kernel="rbf")

# set up GridSearchCV()


model_cv = GridSearchCV(estimator = model, 
                        param_grid = hyper_params, 
                        scoring= 'accuracy', 
                        cv = folds, 
                        verbose = 1,
                        return_train_score=True)      

# fit the model
model_cv.fit(X_train, Y_train) 

Fitting 5 folds for each of 12 candidates, totalling 60 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  60 out of  60 | elapsed: 12.3min finished


GridSearchCV(cv=KFold(n_splits=5, random_state=101, shuffle=True),
             error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000],
                          'gamma': [0.01, 0.001, 0.0001]}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='accuracy', verbose=1)

In [ ]:
cv_results = pd.DataFrame(model_cv.cv_results_)
cv_results("")

mean_fit_time  std_fit_time  ...  mean_train_score  std_train_score
0        3.169755      0.023518  ...          0.844679         0.001514
1        6.847813      0.029770  ...          0.683821         0.003021
2       13.092906      0.020784  ...          0.227982         0.011507
3        1.916264      0.006301  ...          0.929304         0.000746
4        3.167468      0.010010  ...          0.817857         0.001897
5        6.820265      0.029955  ...          0.683643         0.002608
6        2.047501      0.013447  ...          0.978411         0.000249
7        2.181161      0.011364  ...          0.878768         0.002262
8        3.199864      0.006443  ...          0.813179         0.001815
9        2.267004      0.007242  ...          0.997357         0.000237
10       2.492804      0.023888  ...          0.929982         0.001921
11       2.337796      0.026264  ...          0.860679         0.002125

[12 rows x 22 columns]

In [ ]:
best_score = model_cv.best_score_
best_hyperparams = model_cv.best_params_

print("The best test score is {0} corresponding to hyperparameters {1}".format(best_score, best_hyperparams))

The best test score is 0.9517142857142857 corresponding to hyperparameters {'C': 1000, 'gamma': 0.01}


In [ ]:
# model with optimal hyperparameters

# model
model = SVC(C=1000, gamma=0.01, kernel="rbf")

model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

# metrics
print("accuracy", metrics.accuracy_score(Y_test, y_pred), "\n")
print(metrics.confusion_matrix(Y_test, y_pred), "\n")


accuracy 0.9596666666666667 

[[206   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0
    0   0   0   0   0   0   2   0]
 [  0 211   0   2   1   0   1   0   0   0   0   0   0   0   0   0   0   1
    2   0   0   0   0   0   0   0]
 [  0   0 220   0   3   0   4   1   0   0   0   0   0   0   2   0   0   0
    0   0   0   0   0   0   0   0]
 [  0   3   0 236   0   1   0   1   0   1   0   0   0   2   2   0   0   1
    1   0   0   0   0   0   0   0]
 [  0   0   1   0 225   1   4   0   0   0   0   0   0   0   0   0   0   0
    1   0   0   0   0   0   0   2]
 [  0   0   0   1   0 217   0   0   1   1   0   0   0   1   0   3   0   0
    0   0   0   1   0   0   0   0]
 [  0   0   2   3   1   0 209   0   0   0   0   0   1   0   1   0   0   0
    0   0   0   1   1   0   0   0]
 [  0   1   3   5   0   0   2 195   1   1   2   1   1   0   1   0   3   1
    0   0   0   0   0   0   0   0]
 [  0   0   0   1   0   1   0   0 203   8   0   0   0   0   0   0   1   0
    0   0   0   0   0   

In [ ]:
print(metrics.classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           A       0.99      0.99      0.99       209
           B       0.91      0.97      0.94       218
           C       0.96      0.96      0.96       230
           D       0.93      0.95      0.94       248
           E       0.93      0.96      0.95       234
           F       0.94      0.96      0.95       225
           G       0.92      0.95      0.94       219
           H       0.93      0.90      0.91       217
           I       0.95      0.94      0.95       215
           J       0.94      0.95      0.95       220
           K       0.97      0.93      0.95       245
           L       0.99      0.98      0.98       237
           M       0.97      0.98      0.98       234
           N       0.96      0.97      0.96       251
           O       0.96      0.95      0.96       221
           P       0.97      0.95      0.96       265
           Q       0.96      0.96      0.96       235
           R       0.95    